package entity;
// Generated Mar 31, 2020, 5:32:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *MyAccountt generated by hbm2java
 */
public class MyAccount implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String address;
     private String phone;
     private Date birthday;
     private String fullName;
     private String password;

    public MyAccount() {
    }

	
    public MyAccount(String userName, String fullName, String password) {
        this.userName = userName;
        this.fullName = fullName;
        this.password = password;
    }
    public MyAccount(String userName, String address, String phone, Date birthday, String fullName, String password) {
       this.userName = userName;
       this.address = address;
       this.phone = phone;
       this.birthday = birthday;
       this.fullName = fullName;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

  public String toString() {
        return userName+", "+password+" ,"+password+", "+phone;
    }



}


